#!/usr/bin/env bash
#password story
while IFS=: read -r username _ user_id _ _ home_dir shell _; do
	echo "The user $username is part of the $user_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
